name: EcoTrack CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  install-check:
    name: Vérification des dépendances
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        service:
          - service-auth
          - service-containers
          - service-routes
          - service-iot
          - service-gamification
          - service-analytics
          - api-gateway

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: microservices/${{ matrix.service }}/package-lock.json

      
      - name: Install Snyk CLI
        run: npm install -g snyk

      - name: Run Snyk scan — ${{ matrix.service }}
        env:
          SNYK_TOKEN: ${{ secrets.SNYK }}
        run: |
          cd microservices/${{ matrix.service }}
          snyk test --severity-threshold=high

  build-docker:
    name: Build Docker images
    runs-on: ubuntu-latest
    needs: install-check

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build all services
        working-directory: microservices
        run: docker compose build